language: cpp
sudo: required

before_install:
  -  APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/install-prereqs-ubuntu.sh -y && . ~/.profile && popd

script: 
  - ls
  - cd ArduCopter
  - make configure
  - make px4-v2