language: cpp
sudo: required

before_install:
  -  APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/install-prereqs-ubuntu.sh -y && . ~/.profile && popd

script: 
  - cd ./nwind21/ardupilot/ArduCopter
